### ISSUE TITLE
Using CHOST in dev-lang/dmd

### ISSUE THREAD

**Issue by zunkree** [gentoo/dlang#15]
Hi

What you think about using $CHOST for dev-lang/dmd instalations and move it into paths similar to gcc. I mean:

* /usr/lib/x86_64-pc-linux-gnu/dmd/${PV} for imports and libs
* /usr/share/dmd-data/x86_64-pc-linux-gnu/${PV} for docs, licenses, man pages, etc.
* /usr/x86_64-pc-linux-gnu/dmd-bin/${PV} for binaries and configs

Also, we can setup dev-util/dlang-tools in /usr/x86_64-pc-linux-gnu/dmd-bin/${PV}/ too. And we can set SYSCONFDIR for dmd, which allow us to create /usr/bin/dmd-${PV} and use it separately.

**Comment by mleise** [comment]
What is the benefit of a $CHOST path, aside from being more consistent with gcc? Ebuilds for dmd and ldc2 would have to be altered. The paths look good. I'd just like to mention that the dlang-tools ebuild can be compiled with dmd, gdc or ldc2. The idea was that you should be able to compile and use these tools even if all you have is e.g. ldc2 installed.

/usr/bin/dmd-${PV} symlinks are certainly possible and don't require changes to SYSCONFDIR. In fact the symlink /etc/dmd.conf is just there for convenience. I.e. `sudo ln -s /opt/dmd-2.067/bin/dmd /usr/bin/dmd-2.067` is all it takes. These symlinks would be in line with how separate Python and Ruby version are installed. I'll add them next time I touch the dmd ebuilds.

**Comment by mleise** [comment]
`/usr/bin/dmd-x.yyy` symlinks are now in place. `dlang-tools` are not dmd specific and should not be in a "proprietary" directory for that reason. Given a gdc or ldc2 with same level front-end version they should compile with those alternative compilers, too. This allows for a gdc or ldc2 only Dlang environment with `rdmd`, `ddemangle` and `dustmite`.

For the $CHOST idea I don't see much benefit. Feel free to elaborate on this more. I'll close the issue in no sooner than 2 weeks from now.
