### ISSUE TITLE
Associative arrays in dlang-compilers.eclass

### ISSUE THREAD

**Issue by Vality** [gentoo/dlang#17]
The dlang-compilers eclass and some of the associated ebuilds are using the bash 4 associative arrays. 
```bash
	declare -gA __dlang_dmd_frontend_mapping
	declare -gA __dlang_gdc_frontend_mapping
	declare -gA __dlang_ldc2_frontend_mapping
```
These are not supported in ebuilds as they are not available in bash 3.2 as specified as the required bash version in the Gentoo PMS (https://dev.gentoo.org/~ulm/pms/head/pms.html). This is causing the build to fail when using the paludis package manager or older versions of portage.

**Comment by mleise** [comment]
As of Paludis 2.6.0 (released in early May 2016), EAPI=6 is supported, which enables bash 4.2. I'll start reintroducing AAs where they are useful.
