### ISSUE TITLE
Fail compiling LDC2 0.16.1

### ISSUE THREAD

**Issue by AndreaOrru** [gentoo/dlang#28]
Compilation fails under Funtoo Stable, using CMake 3.3.2.
Looks like an easy fix, patching the CMakeLists.txt should be enough.

<pre><code> * Package:    dev-lang/ldc2-0.16.1
 * Repository: dlang
 * USE:        amd64 elibc_glibc kernel_linux userland_GNU
 * FEATURES:   preserve-libs sandbox userpriv usersandbox
>>> Unpacking source...
>>> Unpacking ldc-0.16.1-src.tar.gz to /var/tmp/portage/dev-lang/ldc2-0.16.1/work
>>> Source unpacked in /var/tmp/portage/dev-lang/ldc2-0.16.1/work
>>> Preparing source in /var/tmp/portage/dev-lang/ldc2-0.16.1/work/ldc-0.16.1-src ...
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/dev-lang/ldc2-0.16.1/work/ldc-0.16.1-src ...
>>> Working in BUILD_DIR: "/var/tmp/portage/dev-lang/ldc2-0.16.1/work/ldc2-0.16.1_build"
cmake --no-warn-unused-cli -C /var/tmp/portage/dev-lang/ldc2-0.16.1/work/ldc2-0.16.1_build/gentoo_common_config.cmake -G Unix Makefiles -DCMAKE_INSTALL_PREFIX=/usr -DD_VERSION=2 -DCMAKE_INSTALL_PREFIX=/opt/ldc2-0.16 -DCMAKE_BUILD_TYPE=Gentoo -DCMAKE_INSTALL_DO_STRIP=OFF -DCMAKE_USER_MAKE_RULES_OVERRIDE=/var/tmp/portage/dev-lang/ldc2-0.16.1/work/ldc2-0.16.1_build/gentoo_rules.cmake -DCMAKE_TOOLCHAIN_FILE=/var/tmp/portage/dev-lang/ldc2-0.16.1/work/ldc2-0.16.1_build/gentoo_toolchain.cmake  /var/tmp/portage/dev-lang/ldc2-0.16.1/work/ldc-0.16.1-src
Not searching for unused variables given on the command line.
loading initial cache file /var/tmp/portage/dev-lang/ldc2-0.16.1/work/ldc2-0.16.1_build/gentoo_common_config.cmake
-- The C compiler identification is GNU 4.9.3
-- The CXX compiler identification is GNU 4.9.3
-- Check for working C compiler: /usr/bin/x86_64-pc-linux-gnu-gcc
-- Check for working C compiler: /usr/bin/x86_64-pc-linux-gnu-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/x86_64-pc-linux-gnu-g++
-- Check for working CXX compiler: /usr/bin/x86_64-pc-linux-gnu-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found LLVM: /usr (found suitable version "3.7.0", minimum required is "3.1") 
-- Found LibConfig: /usr/include  
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/x86_64-pc-linux-gnu-gcc
-- LDC version identifier: 0.16.0
-- Check if the system is big endian
-- Searching 16 bit integer
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Using unsigned short
-- Check if the system is big endian - little endian
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Looking for setupterm in tinfo
-- Looking for setupterm in tinfo - not found
-- Looking for setupterm in terminfo
-- Looking for setupterm in terminfo - not found
-- Looking for setupterm in curses
-- Looking for setupterm in curses - found
-- Using path for Intrinsics.td: /usr/include
-- Looking for _SC_ARG_MAX
-- Looking for _SC_ARG_MAX - found
-- Check size of void*
-- Check size of void* - done
-- <<< Gentoo configuration >>>
Build type      Gentoo
Install path    /opt/ldc2-0.16
Compiler flags:
C               -march=core-avx2 -O2 -pipe 
C++             -march=core-avx2 -O2 -pipe 
Linker flags:
Executable       -Wl,-O1 -Wl,--sort-common -Wl,--as-needed
Module           -Wl,-O1 -Wl,--sort-common -Wl,--as-needed
Shared           -Wl,-O1 -Wl,--sort-common -Wl,--as-needed

-- Configuring done
CMake Error at CMakeLists.txt:426 (add_library):
  Target "LDCShared" links to item "-L/usr/lib64 " which has leading or
  trailing whitespace.  This is now an error according to policy CMP0004.

CMake Error at CMakeLists.txt:481 (add_executable):
  Target "gen_gccbuiltins" links to item "-L/usr/lib64 " which has leading or
  trailing whitespace.  This is now an error according to policy CMP0004.

CMake Error at CMakeLists.txt:426 (add_library):
  Target "LDCShared" links to item "-L/usr/lib64 " which has leading or
  trailing whitespace.  This is now an error according to policy CMP0004.

CMake Warning (dev) in CMakeLists.txt:
  Policy CMP0022 is not set: INTERFACE_LINK_LIBRARIES defines the link
  interface.  Run "cmake --help-policy CMP0022" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  Target "LDCShared" has an INTERFACE_LINK_LIBRARIES property.  This should
  be preferred as the source of the link interface for this library but
  because CMP0022 is not set CMake is ignoring the property and using the
  link implementation as the link interface instead.

  INTERFACE_LINK_LIBRARIES:

    -lLLVMOption;-lLLVMLTO;-lLLVMObjCARCOpts;-lLLVMLinker;-lLLVMipo;-lLLVMVectorize;-lLLVMDebugInfoDWARF;-lLLVMBitWriter;-lLLVMAsmParser;-lLLVMX86Disassembler;-lLLVMX86AsmParser;-lLLVMX86CodeGen;-lLLVMSelectionDAG;-lLLVMAsmPrinter;-lLLVMCodeGen;-lLLVMScalarOpts;-lLLVMProfileData;-lLLVMInstCombine;-lLLVMInstrumentation;-lLLVMTransformUtils;-lLLVMipa;-lLLVMX86Desc;-lLLVMObject;-lLLVMMCParser;-lLLVMBitReader;-lLLVMMCDisassembler;-lLLVMX86Info;-lLLVMX86AsmPrinter;-lLLVMX86Utils;-lLLVMCppBackendCodeGen;-lLLVMTarget;-lLLVMMC;-lLLVMAnalysis;-lLLVMCore;-lLLVMCppBackendInfo;-lLLVMSupport;-lpthread;curses;-L/usr/lib64 ;dl

  Link implementation:

    -lLLVMOption;-lLLVMLTO;-lLLVMObjCARCOpts;-lLLVMLinker;-lLLVMipo;-lLLVMVectorize;-lLLVMDebugInfoDWARF;-lLLVMBitWriter;-lLLVMAsmParser;-lLLVMX86Disassembler;-lLLVMX86AsmParser;-lLLVMX86CodeGen;-lLLVMSelectionDAG;-lLLVMAsmPrinter;-lLLVMCodeGen;-lLLVMScalarOpts;-lLLVMProfileData;-lLLVMInstCombine;-lLLVMInstrumentation;-lLLVMTransformUtils;-lLLVMipa;-lLLVMX86Desc;-lLLVMObject;-lLLVMMCParser;-lLLVMBitReader;-lLLVMMCDisassembler;-lLLVMX86Info;-lLLVMX86AsmPrinter;-lLLVMX86Utils;-lLLVMCppBackendCodeGen;-lLLVMTarget;-lLLVMMC;-lLLVMAnalysis;-lLLVMCore;-lLLVMCppBackendInfo;-lLLVMSupport;-lpthread;curses;-L/usr/lib64;dl

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at CMakeLists.txt:513 (add_executable):
  Target "ldmd2" links to item "-L/usr/lib64 " which has leading or trailing
  whitespace.  This is now an error according to policy CMP0004.

CMake Error at CMakeLists.txt:426 (add_library):
  Target "LDCShared" links to item "-L/usr/lib64 " which has leading or
  trailing whitespace.  This is now an error according to policy CMP0004.

CMake Error at CMakeLists.txt:426 (add_library):
  Target "LDCShared" links to item "-L/usr/lib64 " which has leading or
  trailing whitespace.  This is now an error according to policy CMP0004.

-- Generating done
-- Build files have been written to: /var/tmp/portage/dev-lang/ldc2-0.16.1/work/ldc2-0.16.1_build
 * ERROR: dev-lang/ldc2-0.16.1::dlang failed (configure phase):
 *   cmake failed
 * 
 * Call stack:
 *     ebuild.sh, line   93:  Called src_configure
 *   environment, line 2790:  Called cmake-utils_src_configure
 *   environment, line  664:  Called _execute_optionally 'src_configure'
 *   environment, line  224:  Called enable_cmake-utils_src_configure
 *   environment, line 1007:  Called die
 * The specific snippet of code:
 *       "${CMAKE_BINARY}" "${cmakeargs[@]}" "${CMAKE_USE_DIR}" || die "cmake failed";
 * 
 * If you need support, post the output of `emerge --info '=dev-lang/ldc2-0.16.1::dlang'`,
 * the complete build log and the output of `emerge -pqv '=dev-lang/ldc2-0.16.1::dlang'`.
 * The complete build log is located at '/var/tmp/portage/dev-lang/ldc2-0.16.1/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/dev-lang/ldc2-0.16.1/temp/environment'.
 * Working directory: '/var/tmp/portage/dev-lang/ldc2-0.16.1/work/ldc2-0.16.1_build'
 * S: '/var/tmp/portage/dev-lang/ldc2-0.16.1/work/ldc-0.16.1-src'
</code></pre>

**Comment by mleise** [comment]
@redstar Any update on this? Seems to be a simple whitespace issue.

**Comment by mleise** [comment]
Should be working now. Upstream added the fix as well.
