### ISSUE TITLE
Relation to ldc overlay

### ISSUE THREAD

**Issue by gagern** [gentoo/dlang#29]
How does this overlay here relate to https://github.com/ldc-developers/gentoo-overlay? Are they compatible? Is this a superset of that? Can you offer advice for people to help them choose between these?

**Comment by redstar** [comment]
This overlay contains a lot of D related stuff - e.g. compilers (dmd, gdc, ldc) and tools (dub) and so on.
The LDC overlay contains only an ldc ebuild. These ebuilds may be more cutting edge.
General advice is to use this overlay if you are not only focused on ldc.

**Comment by mleise** [comment]
Up until this question I didn't know ldc-developers/gentoo-overlay was still actively maintained. Anyways I'm closing this as it is more a direct question than an issue report and has an answer now.
