### ISSUE TITLE
DCD-0.7.0 fails to link with dmd-2.069.1

### ISSUE THREAD

**Issue by ivan-timokhin** [gentoo/dlang#30]
See [build log](https://gist.github.com/ivan-timokhin/2ebc0f2d940dead3f877) for details.
There seems to be a lot of undefined references to `containers.openhashset.__array`.

**Comment by mleise** [comment]
Thanks for reporting. The issue slipped by me as it doesn't occur with `DMDFLAGS="-release -O -noboundscheck -wi"`. You might want to set at least `-O -wi`, too to get optimized builds and have compilation continue after warnings. See: https://wiki.gentoo.org/wiki/Dlang#Usage

**Comment by ivan-timokhin** [comment]
Thanks to you!
