### ISSUE TITLE
Cannot emerge LDC2 and dub

### ISSUE THREAD

**Issue by beniquezsd** [gentoo/dlang#38]
Hello,

I'm having a problem installing ldc2 and dub after the latest set of gentoo base updates.
I've recently upgraded my system, and it appears that ldc2-0.15.1-r1 depends on libconfig < 1.5.
This is a problem because it seems that the only version of libconfig in the portage tree is 1.5:0.

To work around this,I have attempted to unmask  ldc2-1.7.0-r1, (dub does not have a USE flag for version ldc2_0_16) but when I attempt to use the latest ldc2 ebuild, I get the following error message:

```
# emerge -av ldc2 dub

These are the packages that would be merged, in order:

Calculating dependencies                       C

!!! Problem resolving dependencies for dev-util/dub
... done!

!!! The ebuild selected to satisfy "dub" has unmet requirements.
- dev-util/dub-0.9.24::dlang USE="ldc2-0_17 -debug -dmd-2_066 -dmd-2_067 -dmd-2_068 -dmd-2_069 -gdc-4_8_4 -ldc2-0_15" ABI_X86="64"

  The following REQUIRED_USE flag constraints are unsatisfied:
    exactly-one-of ( gdc-4_8_4 ldc2-0_17? ( !amd64 !x86 ) )

  The above constraints are a subset of the following complete expression:
    exactly-one-of ( dmd-2_066? ( !arm ) dmd-2_067? ( !arm ) dmd-2_068? ( !arm ) dmd-2_069? ( !arm ) gdc-4_8_4 ldc2-0_15? ( !arm ) ldc2-0_17? ( !amd64 !x86 ) )
```

Is there any way I can attempt to compile ldc2-0.17.0-r1 on amd64?

**Comment by bittwiddler1** [comment]
In the meantime, I've unmasked ldc2-0.17.0-r1 and compiled dub manually in my home folder for the time being, but I don't understand why the ldc2-0_17 use flag has the x86 and am64 platforms masked?

**Comment by mleise** [comment]
I have to look into it to tell whether it is a bug that ldc2-0_17 is listed as an option. It is correct though that it is disallowed as no stable package may depend on an unstable package. (dub is stable, ldc2-0.17 is (still marked) unstable)
The whole thing is a portage hack that C++ gets around with a single compiler vendor and stable standard library. C++ libraries don't depend on a specific compiler version, but with Dlang you practically need a separate eco system for every compiler release.

**Comment by mleise** [comment]
Compiler USE-flags for dub (and other packages) are listed if there is at least one architecture for which the compiler is at least as stable as the package to be compiled with it. E.g. when ldc2-0.17.0 is unstable on all arches and dub is stable only on _x86_ and _amd64_, but not on _arm_, then the USE flag ldc2-0_17 will only work for people on _arm_ and cause above "unmet requirement" on _x86_ and _amd64_.
