### ISSUE TITLE
wrong dmd.conf on x32 systems

### ISSUE THREAD

**Issue by itspec-ru** [gentoo/dlang#40]
On x32 system the phobos library install in /opt/dmd-${PV}/**lib** directory.
But dmd.conf contain **lib32**

my config /opt/dmd-2.067/bin/dmd.conf:
```
[Environment]
DFLAGS=-I/opt/dmd-2.067/import -L--export-dynamic -defaultlib=phobos2 -L-L/opt/dmd-2.067/lib32 -L-rpath -L/opt/dmd-2.067/lib32

```

ls -l /opt/dmd-2.067
total 40
drwxr-xr-x 2 root root 4096 Apr 16 23:43 bin
-rw-r--r-- 1 root root 2373 Apr 16 22:54 dmd-backendlicense.txt
-rw-r--r-- 1 root root 1338 Apr 16 22:54 dmd-boostlicense.txt
-rw-r--r-- 1 root root 1453 Apr 16 22:54 druntime-LICENSE.txt
drwxr-xr-x 3 root root 4096 Apr 16 22:55 html
drwxr-xr-x 5 root root 4096 Apr 16 22:55 import
drwxr-xr-x 2 root root 4096 Apr 16 22:55 lib
drwxr-xr-x 4 root root 4096 Apr 16 12:02 man
-rw-r--r-- 1 root root 1338 Apr 16 22:54 phobos-LICENSE.txt
drwxr-xr-x 3 root root 4096 Apr 16 22:55 samples

**Comment by mleise** [comment]
If you mean x86 (you got me confused, but I figured many people incorrectly refer to x86 with x32 (which is amd64 with 32-bit pointers)), then please try the unstable packages I uploaded yesterday and tell me how they work out for you. I tested them on an IBM T23 (Pentium III).

**Comment by itspec-ru** [comment]
Now OK. I had outdated overlay (last commit 14 apr).
Thank you. Excuse for the taken-away time

**Comment by mleise** [comment]
You're welcome. It was just a coincidence that I fixed that bug one day before you installed dmd.
