### ISSUE TITLE
ldc2 ebuilds missing bootstrap dependencies/useflags

### ISSUE THREAD

**Issue by Calrama** [gentoo/dlang#56]
The useflags (and dependencies on) that are present for `dmd` to select an appropriate bootstrap compiler are missing from `ldc2`. As such, one cannot just build a recent ldc2 ebuild without installing a d compiler first manually.

**Comment by mleise** [comment]
Thanks, it should be fixed now.

**Comment by Calrama** [comment]
Yes, it works as expected now, thank you.
