### ISSUE TITLE
Link error with ldc2-1.3.0-r1 without `static-libs` USE flag

### ISSUE THREAD

**Issue by Calrama** [gentoo/dlang#63]
As [mentioned here](https://github.com/gentoo/dlang/commit/475ab97bac895c61a94ff58793dc3456ef2485f2#commitcomment-22998571), patching the ldc2 config to always use the '-shared' suffix for linking breaks linking when only shared libraries are built, because they then do not have that suffix.

**Comment by mleise** [comment]
Thx, should be solved now.
