### ISSUE TITLE
Unable to build dmd:2.067 with glibc-2.25-r4

### ISSUE THREAD

**Issue by doctaweeks** [gentoo/dlang#66]
```
In file included from root/port.c:587:0:
/usr/include/bits/mathdef.h:19:3: error: #error "Never use <bits/mathdef.h> directly; include <complex.h> instead"
# error "Never use <bits/mathdef.h> directly; include <complex.h> instead"
```

I have not checked older C++ dmd versions for this problem.

It doesn't look like this was a result of a change in glibc - the preprocessor check has existed for quite a few versions - at least back to 2.17.

**Comment by mleise** [comment]
I'm still on glibc-2.23-r4 and it compiles just fine. I'll probably just patch that line to include <complex.h> in the older dmd versions, if there is no catch (like symbol collisions when including more than just mathdef.h).
