### ISSUE TITLE
cannot build tilix dmd-2_080

### ISSUE THREAD

**Issue by kroppt** [gentoo/dlang#72]
https://github.com/gnunn1/tilix/issues/1540

tilix dev suggested updating from 1.7.1 to the current 1.8.5

**Comment by mleise** [comment]
The new vte version in Gentoo allows me to finally offer more recent gtkd versions that are required by even more recent tilix versions. Stay tuned.

**Comment by mleise** [comment]
I have blacklisted 2.080 and above for Tilix 1.7.1 and added Tilix 1.8.5 as a new ebuild. I haven't tested it thoroughly yet since I'm mostly on stable and the update process for GtkD's dependencies looked intimidating.
