### ISSUE TITLE
Can't build LDC when the LLVM linker is installed

### ISSUE THREAD

**Issue by BorisCarvajal** [gentoo/dlang#73]
Got this cryptic message while I was installing LDC:

`CommandLine Error: Option 'asm-instrumentation' registered more than once!`

Further investigation led me to this issue ldc-developers/ldc#2661.

It seems that if you have the option LDC_WITH_LLD=ON (i.e. sys-devel/lld is installed)
but you are linking against shared LLVM libraries then it's not going to work.
Gentoo only supports shared LLVM, so LDC_WITH_LLD should be explicitly disabled for now.

Also LDC 1.11 supports LLVM up to 6 not 7. With the version 7.0 I got a error about some header not found (file renamed or moved from 6 to 7 I think).

**Comment by mleise** [comment]
Good catch about LLVM 7, I must have been looking at the latest 0.12 change log. I'll add the `LDC_WITH_LDD=OFF` flag.
