### ISSUE TITLE
[dlang overlay] GCC 7.3 failed to build because old GDC repo has been archived

### ISSUE THREAD

**Issue by donlzx** [gentoo/dlang#74]
Old GDC repo has been archived (https://github.com/D-Programming-GDC/gdc-archived), thus making GCC 7.3 failed to build after adding the dlang overlay.

In /var/lib/layman/dlang/sys-devel/gcc/gcc-7.3.0-r3.ebuild file,
```EGIT_REPO_URI="https://github.com/D-Programming-GDC/GDC.git"```
should be
```EGIT_REPO_URI="https://github.com/D-Programming-GDC/gdc-archived.git"```

**Comment by mleise** [comment]
Thank you. I'll fix it.

**Comment by mleise** [comment]
Thank you. I'll fix it.
