### ISSUE TITLE
GDC 9.1.0 should be listed in dlang-compilers.eclass

### ISSUE THREAD

**Issue by SolarAaron** [gentoo/dlang#77]
This is since the gcc-9.1.0 package in portage supports the 'd' use flag which builds gdc.

**Comment by mleise** [comment]
Due to how USE dependencies work, it will be added when it reaches stable on some archs. (Otherwise repoman will complain about stable packages depending on an unstable compiler.)

**Comment by mleise** [comment]
Heads-up: The GDC version in GCC 9.1.0 is based on the last C++ front-end, which is language version 2.076 from Oct 2017. This is usually done to have a bootstrap compiler for more recent versions available. Didn't look into it further.

**Comment by MoritzMaxeiner** [comment]
FWIF: Funtoo's GCC 9 catpkg can build dmd 2.086.

**Comment by Kokokokoka** [comment]
gcc 9 is stable now

**Comment by mleise** [comment]
> gcc 9 is stable now

Yes, I think this issue can be closed as GCC 9.2.0 and 9.3.0 are available for Dlang packages now. Will update the other packages later today.
