### ISSUE TITLE
tilix doesn't know about newer ldc2 versions

### ISSUE THREAD

**Issue by KingDuckZ** [gentoo/dlang#82]
As per the title, tilix is forcing me to keep ldc2-1_16 installed because it doesn't have a USE flag for more recent versions.

The situation is made even worse now that I updated to ldc2-1.19.0 since ldc2 itself only has USE flags for up to v1.17. This means that I have 3 different versions of ldc2 installed for no apparent reason.

**Comment by mleise** [comment]
Tilix lacks these USE flags, because it is incompatible with the latest Dlang compiler interfaces.
