### ISSUE TITLE
ldc2-1.24.0 line 21: Was expecting token "string". Got ',' instead.

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [gentoo/dlang#85]
build log here https://gist.github.com/Alessandro-Barbieri/f935b3555416cafb479688db7ef37fe5

**Comment by mleise** [comment]
Hello Alessandro! Do you know where `-DADDITIONAL_DEFAULT_LDC_SWITCHES=, "-relocation-model=pic"` comes from? I don't have that on the cmake command line when I build LDC2 and it looks like that comma is causing the problem for the parser.

**Comment by mleise** [comment]
Hello Alessandro! It may be that the ldc2.conf format changed at some point. I'm not using hardened Gentoo. Does this error pop up with all current versions of the ldc ebuild or did it start with 1.24.0?

**Comment by mleise** [comment]
I already answered it myself. I'll remove the superfluous comma from all ebuilds. Thanks for reporting the issue.

**Comment by mleise** [comment]
Can you help me out here and test if the build completes if you remove the superfluous comma from the ebuilds where it says: `detect_hardened && mycmakeargs+=( -DADDITIONAL_DEFAULT_LDC_SWITCHES=', "-relocation-model=pic"' )`?
On my end I get the error `ldc2: for the --relocation-model option: Cannot find option named 'pic-link-defaultlib-shared'!` and if that's the same on hardened, you'd have to fix the ebuild yourself and provide the patch.

**Comment by Alessandro-Barbieri** [comment]
Try this: `-DADDITIONAL_DEFAULT_LDC_SWITCHES=' "-relocation-model=pic", '` it seems to work

**Comment by mleise** [comment]
Haha, I see my mistake now. Thank you it works now for me. Will be fixed in the next update!
